#!/bin/bash
set -e
REALPATH=$(realpath "$0" --relative-to="$HOME")
DIRNAME=$(dirname "$REALPATH")

pushd ~ > /dev/null
for file in .dircolors .gitconfig .jedrc .plan .vimrc .tmux.conf .gdbinit ; do
	ln -sf "$DIRNAME/$file" .
done
ln -sf $DIRNAME/.bash_* .

mkdir -p .mutt
ln -sf .mutt/bremen.muttrc .muttrc
cd ~/.mutt
ln -sf ../$DIRNAME/mutt/* .

mkdir -p ~/.ssh
cd ~/.ssh
ln -sf ../$DIRNAME/.ssh/* .
popd > /dev/null

