#!/bin/sh
set -e
cd ~
install dotfiles/.gitconfig .
ln -sf dotfiles/.bash_* .
ln -s dotfiles/.gdbinit
ln -s dotfiles/.tmux.conf
ln -s dotfiles/.jedrc
ln -sf dotfiles/.plan
#ln -s dotfiles/.vimrc
mkdir .mutt
cd .mutt
ln -sf .mutt/bremen.muttrc .muttrc
ln -sf ../dotfiles/mutt/* .
ln -sf dotfiles/.bash_profile
mkdir -p ../.ssh
cd ../.ssh
ln -sf ../dotfiles/.ssh/* .
